project:
  type: website

website:
  page-navigation: true
  title: "Supplementary material for a network meta-analysis of employment and skills interventions designed to assist young people to enter the labour market in high income countries"
  description: ""
  site-url: "https://davetayl-r.github.io/youth-employment-nma-paper"
  repo-url: https://github.com/davetayl-r/youth-employment-nma-paper

  open-graph: true

  page-footer:
    right: "Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)"
    background: "#212529"
    
format:
  html:
    theme: 
     - cosmo
     - theme.scss
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true

editor: visual    
    
freeze: auto